// components/Button/index.jsx
import React from 'react';

import css from './Button.module.scss';

const Button = ({
  onClick = null,
  type = 'button',
  secondary,
  className,
  children,
}) => {
  return (
    <button
      type={type}
      onClick={onClick}
      className={`${css.button} ${className} ${secondary && css.secondary}`}
    >
      {children}
    </button>
  );
};

export default Button;

// src/components/Button/Button.svelte
<script>
  import css from './Button.module.scss'

  export let cname
  export let secondary // boolean
  export let type = 'button' // or 'submit' or 'reset'
  export let onClick
</script>

<button
  {type}
  {onClick}
  class={`${css.button} ${cname} ${secondary && css.secondary}`}
>
  <slot />
</button>
