// src/components/Hero/PostHero.svelte
<script>
  import css from './PostHero.module.scss'
  import Tag from '../Tag/Tag.svelte'
  import PostMetadata from '../PostMetadata/PostMetadata.svelte'

  export let data
  export let date
  export let stats
</script>

<section class={css.hero}>
  <div class={css.postPic}>
    <img src={data.pic} alt={data.description} width="300" height="300" />
  </div>
  <div class={css.postData}>
    <div class={css.tags}>
      {#each data.tags as { tag }}
        <Tag to={`/tags#${tag}`} {tag} />
      {/each}
    </div>
    <div class={css.title}>
      <h1>{data.title}</h1>
      <p>{data.description}</p>
    </div>
    <PostMetadata cname={css.metadata} {date} {stats} />
  </div>
</section>

// src/components/Hero/PostHero.tsx
import React from 'react';
import Image from 'next/image';

import PostMetadata from '@components/PostMetadata';
import Tag from '@components/Tag';

import { StatsType } from '@components/types';

import css from './PostHero.module.scss';

type Data = {
  title: string;
  description: string;
  tags: string[];
  pic: string;
};

type Props = {
  date: string;
  data: Data;
  stats: StatsType;
};

const PostHero = ({ date, data, stats }: Props) => {
  return (
    <section className={css.hero}>
      <div className={css.postPic}>
        <Image
          src={data.pic}
          alt={data.description}
          fill
          sizes="(max-width: 768px) 300px,
                  500px"
        />
      </div>
      <div className={css.postData}>
        <div className={css.tags}>
          {data.tags.map((tag, index) => {
            return <Tag key={index} tag={tag} to={`/tags#${tag}`} />;
          })}
        </div>
        <div className={css.title}>
          <h1>{data.title}</h1>
          <p>{data.description}</p>
        </div>
        <PostMetadata cname={css.metadata} date={date} stats={stats} />
      </div>
    </section>
  );
};

export default PostHero;
