// src/components/Navbar/NavItems.svelte
<script>
  import { onMount } from 'svelte'
  import NavLink from './NavLink.svelte'
  import css from './NavItems.module.scss'

  const pages = [
    {
      name: 'Home',
      href: '/'
    },
    {
      name: 'Photos',
      href: '/photos'
    },
    {
      name: 'Blog',
      href: '/blog'
    }
  ]

  export let menuHandler

  onMount(() => {
    // Perform any necessary actions on component mount
    console.log('Component mounted')
  })
</script>

<ul class={css.navLinks}>
  {#each pages as { name, href }, index}
    <NavLink key={index} {href} on:click={menuHandler}>
      {name}
    </NavLink>
  {/each}
</ul>

// components/Navbar/NavItems.jsx
import React from 'react';

import NavLink from './NavLink';

import styles from './NavItems.module.scss';

const NavItems = ({ menuHandler }) => {
  return (
    <ul className={styles.navLinks}>
      <NavLink href="/" onClick={menuHandler}>
        About
      </NavLink>
      <NavLink href="/posts" onClick={menuHandler}>
        Blog
      </NavLink>
      <NavLink href="/photos" onClick={menuHandler}>
        Photos
      </NavLink>
    </ul>
  );
};

NavItems.defaultProps = {
  menuHandler: () => null,
};

export default NavItems;
