// components/PostThumbnail/index.jsx
import React from 'react';
import Link from 'next/link';

import styles from './PostThumbnail.module.scss';

const Post = ({ id, date, title, author, tag, description }) => {
  const formattedDate = new Date(date).toDateString();

  const tags = tag.split(', ');

  return (
    <div className={styles.postContainer}>
      <Link href={`/posts/${id}`}>
        <h1>{title}</h1>
      </Link>
      <p className={styles.description}>{description}</p>
      <div className={styles.tags}>
        {tags.map((tag, index) => {
          return (
            <p key={index} className={styles.tag}>
              {tag}
            </p>
          );
        })}
      </div>
      <div className={styles.data}>
        <p className={styles.date}>{formattedDate}</p>
        <p>&bull;</p>
        <Link href={`/posts/${id}`}>
          <a className={styles.readMore}>Read post...</a>
        </Link>
      </div>
    </div>
  );
};

export default Post;

// src/components/PostThumbnail/PostThumbnail.svelte
<script lang="ts">
  import FormattedDate from '../FormattedDate/FormattedDate.svelte';
  import css from './PostThumbnail.module.scss';

  export let post: {
    id: string;
    data: {
      title: string;
      description: string;
      date: Date;
      image: string;
    };
  };
</script>

<div class={css.article}>
  <div class={css.container}>
    <div class={css.head}>
      <div class={css.date}>
        <FormattedDate date={post.data.date} />
      </div>
      <a class={css.image} href={`/blog/${post.id}`}>
        <img src={post.data.image} alt={post.data.title} />
      </a>
    </div>
    <div class={css.content}>
      <h2 class={css.title}>
        <a href={`/blog/${post.id}`}>{post.data.title}</a>
      </h2>
      <p class={css.description}>{post.data.description}</p>
    </div>
  </div>
</div>
