// src/components/Navbar/Navbar.svelte
<script>
  import { onMount } from 'svelte'
  import FullNav from './FullNav.svelte'
  import MobileNav from './MobileNav.svelte'

  let width = null

  onMount(() => {
    width = window.innerWidth

    const handleResize = () => {
      width = window.innerWidth
    }

    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  })
</script>

{#if width && width <= 600}
  <MobileNav />
{:else}
  <FullNav />
{/if}

// src/components/Navbar/index.tsx
import React, { useEffect, useState } from 'react';

import { FullNav } from './FullNav';
import { MobileNav } from './MobileNav';

const Navbar = () => {
  const [mounted, setMounted] = useState(false);
  const [width, setWidth] = useState<number | null>(null);

  useEffect(() => {
    setMounted(true);
    setWidth(window.innerWidth);
  }, []);

  if (!mounted) return null;

  window.addEventListener('resize', () => {
    setWidth(window.innerWidth);
  });

  // TODO remove 600 and put a not hard-coded variable
  if (width && width <= 600) return <MobileNav />;
  else return <FullNav />;
};

export default Navbar;
