// src/components/Navbar/MobileNav.jsx
import React, { useState } from 'react';

import NavItems from './NavItems';

import MenuIcon from '../../../components/MenuIcon';

import styles from './MobileNav.module.scss';

export const MobileNav = ({ pages }) => {
  const [open, setOpen] = useState(false);

  const handleMenu = () => {
    setOpen(!open);
  };

  return (
    <div className={styles.wrapper}>
      <MenuIcon isOpen={open} handler={handleMenu} />
      <nav className={open ? styles.nav : `${styles.nav} ${styles.collapsed}`}>
        <NavItems menuHandler={handleMenu} pages={pages} />
      </nav>
    </div>
  );
};

// src/components/Navbar/MobileNav.svelte
<script>
  import MenuIcon from '../MenuIcon/MenuIcon.svelte'
  import NavItems from './NavItems.svelte'

  import css from './MobileNav.module.scss'

  let open = false

  const handleMenu = () => {
    open = !open
  }
</script>

<div class={css.wrapper}>
  <MenuIcon isOpen={open} handler={handleMenu} />
  <nav class={open ? css.nav : `${css.nav} ${css.collapsed}`}>
    <NavItems menuHandler={handleMenu} />
  </nav>
</div>
