// src/components/Navbar/index.jsx
import React, { useEffect, useState } from 'react';

import { FullNav } from './FullNav';
import { MobileNav } from './MobileNav';

import { smartphone } from '../../styles/_globals.module.scss';

const Navbar = ({ pages }) => {
  const [mounted, setMounted] = useState(false);
  const [width, setWidth] = useState(null);

  useEffect(() => {
    setMounted(true);
    setWidth(window.innerWidth);
  }, []);

  if (!mounted) return null;

  window.addEventListener('resize', () => {
    setWidth(window.innerWidth);
  });

  if (width <= smartphone) return <MobileNav pages={pages} />;
  else return <FullNav pages={pages} />;
};

export default Navbar;

// src/components/Navbar/Navbar.svelte
<script>
  import { onMount } from 'svelte'
  import FullNav from './FullNav.svelte'
  import MobileNav from './MobileNav.svelte'

  let width = null

  onMount(() => {
    width = window.innerWidth

    const handleResize = () => {
      width = window.innerWidth
    }

    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  })
</script>

{#if width && width <= 600}
  <MobileNav />
{:else}
  <FullNav />
{/if}
