// src/components/Footer/Footer.svelte
<script>
  import css from './Footer.module.scss'
  import {
    RssIcon,
    InstagramIcon,
    GithubIcon,
    LinkedinIcon
  } from 'svelte-feather-icons'

  const YEAR = new Date().getFullYear()
</script>

<footer class={css.footer}>
  <div class={css.content}>
    <div class={css.row}>
      <p class={css.title}>powered by A.I. - Andrea Intelligence</p>
    </div>
    <div class={css.row}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
    </div>
    <div class={css.row}>
      <ul class={css.socialLinks}>
        <li>
          <a href="/feed.xml">
            <RssIcon class={css.icon} />
          </a>
        </li>
        <li>
          <a href="https://instagram.com/andreaiaia" target="_blank">
            <InstagramIcon class={css.icon} />
          </a>
        </li>
        <li>
          <a href="https://github.com/andreaiaia" target="_blank">
            <GithubIcon class={css.icon} />
          </a>
        </li>
        <li>
          <a href="https://linkedin.com/in/andreaiaia/" target="_blank">
            <LinkedinIcon class={css.icon} />
          </a>
        </li>
      </ul>
      <small class={css.credits}>
        <time>{YEAR}</time> © Andrea Bianchi
      </small>
    </div>
  </div>
</footer>

// src/components/Footer/index.jsx
import React from 'react';

import { GitHub, Instagram, Linkedin, Rss } from 'react-feather';

import ThemeSwitcher from '../ThemeSwitcher';
import NotByAi from './NotByAi';

import css from './Footer.module.scss';

const Footer = () => {
  const YEAR = new Date().getFullYear();

  return (
    <footer className={css.footer}>
      <div className={css.content}>
        <ul className={css.links}>
          <li>
            <a href="/feed.xml">
              <Rss className={css.icon} alt="RSS feed" />
            </a>
          </li>
          <li>
            <a href="https://instagram.com/andreaiaia" target="_blank">
              <Instagram className={css.icon} alt="Instagram logo" />
            </a>
          </li>
          <li>
            <a href="https://github.com/andreaiaia" target="_blank">
              <GitHub className={css.icon} alt="Github logo" />
            </a>
          </li>
          <li>
            <a href="https://linkedin.com/in/andreaiaia/" target="_blank">
              <Linkedin className={css.icon} alt="Linkedin logo" />
            </a>
          </li>
        </ul>
        <small className={css.credits}>
          <time>{YEAR}</time> © Andrea Bianchi.
        </small>
        <div>
          <ThemeSwitcher cname={css.switcherStyle} />
        </div>
        <div className={css.notAiBadge}>
          <a href="https://notbyai.fyi/">
            <NotByAi />
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
