// components/Thumbnails/Polaroid.jsx
import React from 'react';
import Image from 'next/image';
import Link from 'next/link';

import styles from './Polaroid.module.scss';

const Polaroid = ({ src, alt, to, title }) => {
  return (
    <div className={styles.container}>
      <Link href={to}>
        <Image
          className={styles.img}
          src={src}
          alt={alt || ''}
          width={350}
          height={350}
        />
        <p className={styles.title}>{title}</p>
      </Link>
    </div>
  );
};

export default Polaroid;

// src/components/Polaroid/Polaroid.svelte
<script>
  import css from './Polaroid.module.scss'

  export let cname
  export let src
  export let alt
  export let to
</script>

{#if to}
  <a class={`${css.container} ${css.link} ${cname || ''}`} href={to || '#'}>
    <div class={css.img}>
      <img {src} alt={alt || ''} width="300" height="300" />
    </div>
    <div class={css.title}>
      <p>{alt}</p>
    </div>
  </a>
{:else}
  <div class={`${css.container} ${cname || ''}`}>
    <div class={css.img}>
      <img {src} alt={alt || ''} width="300" height="300" />
    </div>
    <div class={css.title}>
      <p>{alt}</p>
    </div>
  </div>
{/if}
